- Dockerfile
- Dockerfile-entrypoint.sh
- README
- games/supertux/.gitignore
- games/supertux/build.sh
- lib/util.sh
- runners/residualvm/.gitignore
- runners/residualvm/build.sh
Decided to add [Docker](http://docker.io) support since I wasn't quire sure how to run it directly through lxc. Overall it works quite well.
Saw a few missing dependencies when building residualvm and supertux. Feel free to tweak further.
> Add Docker usage

- games/supertux/build.sh
- lib/util.sh
https://supertuxproject.org/news/2016/09/25/0.5.0
> Update to SuperTux 0.5.0

- runners/web/build.sh
> The best way to predict the future is to create it.
> fix runner folder name inside tgz

- runners/web/build.sh
> So many books, so little time.
> [web] runner repo moved

- runners/web/build.sh
> A smile is a curve that sets everything straight.
> [web] ARMv7 support!

- runners/web/build.sh
> A day without sunshine is like, you know, night.
> [web] fix 32-bit building. add arch flags

- games/commander-genius/build.sh
> Update Commander Genius

- games/openxcom/build.sh
> Added a build script for OpenXcom

- games/moon-buggy/build.sh
> Added moon-buggy to buildbot

- games/commander-genius/.gitignore
- games/commander-genius/build.sh
- lib/util.sh
Update to 2.2.2...
https://github.com/gerstrong/Commander-Genius/releases/tag/v2.2.2
> commander-genius: Update Commander Genius to 2.2.2

- runners/residualvm/build.sh
http://www.residualvm.org/news/20180615/
> ResidualVM: Update to 0.3.1

- runtime/build.sh
- runtime/lutrisrt.py
- runtime/packages
Also replaced the deprecated `--force-yes` option of `apt-get` and added more logging.
> [runtime] Speed up library installation, add lib dependencies for Wine Battle.net 

- games/ultrastar-deluxe/.gitignore
- games/ultrastar-deluxe/build.sh
A distro-independent build of USDX.
https://usdx.eu/
https://github.com/UltraStar-Deluxe/USDX
> [game] UltraStar Deluxe

- runners/libretro/build.sh
This includes the cheats, cursors and RDB database files.
> libretro: Ship the libretro-database files

- tools/winetricks/patches/dotnet471.patch
@strycore Tell me if you want me to enable back its application in the script as well.
> Fix dotnet471 patch for the winetricks version used

- games/supertuxkart/build.sh
- games/supertuxkart/run_game.sh
> Added a build.sh for supertuxkart

- runners/residualvm/.gitignore
- runners/residualvm/build.sh
This fixes https://github.com/lutris/lutris/issues/1691
Should wait until 0.3.2 is out, however.
> Allow static builds of ResidualVM

- runners/libretro/.gitignore
- runners/libretro/build.sh
- runners/libretro/cores.list
Use `libretro-buildbot-recipe.sh` instead.
> libretro: Update core list and core build script

- runners/dolphin/build.sh
- runners/mednafen/build.sh
To save on storage and bandwidth <3.
I'll change it for other runners later.
> Change archive format to XZ for some runners

- runners/libretro/cores.list
Replaces https://github.com/lutris/buildbot/pull/97
> added the latest cores

- games/0ad/build.sh
0.23b-alpha has been out for a moment
> Update 0AD version

- runtime/Ubuntu-18.04.packages
> Add libxtst to Ubuntu 18.04 package list

- tools/winetricks/build.sh
I totally didn't mean to just jam this in! This should be a PR. Is this too hacky to live?
This clones and builds zenity and copies it into the winetricks package. There's a corresponding PR for the Lutris client that will use this if present.
And since this (default) zenity does not use webkit2 or gstreamer, it works on the latest Ubuntu. Or so I hope.
> Adds zenity as part of winetricks.
